#!/bin/bash
# upgrade-shairport-dev.sh -- rebuild shairport-sync from the `development`
# branch instead of `master`, to get its experimental AirPlay 2 remote-control
# support (play/pause/next/previous over D-Bus for AirPlay 2 sessions, which
# the stable release explicitly does not implement -- see AIRPLAY2.md
# upstream: "Remote control facilities are not implemented" for AirPlay 2).
#
# Why this exists: the CEC remote (airplay-cec-remote.py) calls shairport-sync
# D-Bus RemoteControl methods correctly and shairport-sync accepts the calls
# cleanly (no D-Bus error), but nothing reaches the phone, because this
# device runs AirPlay 2 (built 2026-08-31 to stop other apps hijacking the
# stream) and remote control simply has no implementation there in the
# release branch. The development branch is the only place that exists.
#
# Safety: this does NOT touch nqptp, the apt package, or the systemd
# override -- only /usr/local/bin/shairport-sync. The build happens in a
# scratch dir while the CURRENT binary keeps serving traffic; only the final
# install step swaps anything live, and that step backs up the current
# binary first. A generated rollback script is left at
# ~/rollback-shairport-dev.sh that restores it in one command, no rebuild
# needed. The pre-existing, always-available fallback below that is still
# `sudo systemctl revert shairport-sync && sudo systemctl restart
# shairport-sync`, which goes all the way back to apt's classic-AirPlay-1
# package untouched by any of this.
#
# Run as root (installs to /usr/local/bin, restarts a system service):
#   ssh -t airplaymatrix-zero 'sudo bash ~/upgrade-shairport-dev.sh'
# For the ~20min build, prefer running it detached so a dropped SSH session
# doesn't kill it (see [[airplaymatrix-zero-airplay2]] for why):
#   ssh -t airplaymatrix-zero 'sudo setsid nohup bash ~/upgrade-shairport-dev.sh \
#     > ~/upgrade-shairport-dev.log 2>&1 < /dev/null & disown'
# then poll ~/upgrade-shairport-dev.log over a plain (non-sudo) SSH session.
set -euo pipefail

BIN=/usr/local/bin/shairport-sync
SERVICE=shairport-sync.service
HOME_DIR=/home/airplaymatrix
ROLLBACK_SCRIPT="$HOME_DIR/rollback-shairport-dev.sh"

if [[ $EUID -ne 0 ]]; then
  echo "must be run as root (sudo)" >&2
  exit 1
fi

if [[ ! -x "$BIN" ]]; then
  echo "$BIN not found -- expected the existing from-source AirPlay 2 build to be there already" >&2
  exit 1
fi

STAMP="$(date +%Y%m%d%H%M%S)"
BACKUP_BIN="${BIN}.backup-${STAMP}"
OLD_VERSION="$($BIN --version 2>&1 || true)"

echo "current binary: $OLD_VERSION"
echo "backing it up to $BACKUP_BIN before touching anything"
cp -a "$BIN" "$BACKUP_BIN"

# Generate the rollback script now, from the backup we just took, before any
# build risk -- so it exists and is correct even if the build below fails
# partway through.
cat > "$ROLLBACK_SCRIPT" <<ROLLBACK_EOF
#!/bin/bash
# Restores the pre-development-branch shairport-sync binary. Generated by
# upgrade-shairport-dev.sh on ${STAMP}. Run as root:
#   ssh -t airplaymatrix-zero 'sudo bash ~/rollback-shairport-dev.sh'
set -euo pipefail
if [[ \$EUID -ne 0 ]]; then
  echo "must be run as root (sudo)" >&2
  exit 1
fi
if [[ ! -x "$BACKUP_BIN" ]]; then
  echo "backup $BACKUP_BIN is gone -- nothing to roll back to." >&2
  echo "fall back to: sudo systemctl revert $SERVICE && sudo systemctl restart $SERVICE" >&2
  exit 1
fi
echo "stopping $SERVICE"
systemctl stop "$SERVICE"
cp -a "$BACKUP_BIN" "$BIN"
echo "restarting $SERVICE"
systemctl start "$SERVICE"
sleep 1
systemctl is-active --quiet "$SERVICE" && echo "OK: $SERVICE active" || echo "WARNING: $SERVICE not active, check journalctl -u $SERVICE"
echo "restored: \$($BIN --version 2>&1)"
ROLLBACK_EOF
chmod 755 "$ROLLBACK_SCRIPT"
echo "rollback script ready at $ROLLBACK_SCRIPT (usable even if this script fails later)"

BUILD_ROOT="$(mktemp -d)"
cleanup() { rm -rf "$BUILD_ROOT"; }
trap cleanup EXIT

echo "cloning shairport-sync, development branch..."
git clone --quiet --branch development https://github.com/mikebrady/shairport-sync.git "$BUILD_ROOT/shairport-sync"

(
  cd "$BUILD_ROOT/shairport-sync"
  echo "building at commit $(git rev-parse --short HEAD) ($(git log -1 --format=%cd --date=short))"
  autoreconf -fi
  # Identical flag set to the master build this replaces (see setup.sh
  # install_airplay2()) -- same feature parity, only the branch differs.
  ./configure --sysconfdir=/etc \
    --with-alsa --with-soxr --with-avahi --with-ssl=openssl \
    --with-systemd-startup --with-airplay-2 \
    --with-metadata --with-dbus-interface --with-mpris-interface --with-mqtt-client \
    --with-stdout --with-pipe --with-dummy --with-convolution
  make
)

NEW_BIN_PATH="$BUILD_ROOT/shairport-sync/shairport-sync"
NEW_VERSION="$("$NEW_BIN_PATH" --version 2>&1 || true)"
echo "built: $NEW_VERSION"
if ! echo "$NEW_VERSION" | grep -q AirPlay2; then
  echo "built binary doesn't report AirPlay2 support -- refusing to install it" >&2
  exit 1
fi

echo "installing (this is the only step that touches the live binary)"
make -C "$BUILD_ROOT/shairport-sync" install
systemctl restart "$SERVICE"
sleep 1
systemctl is-active --quiet "$SERVICE" || {
  echo "$SERVICE failed to come back up -- rolling back automatically" >&2
  bash "$ROLLBACK_SCRIPT"
  exit 1
}

echo
echo "done. now: $($BIN --version 2>&1)"
echo "was:  $OLD_VERSION"
echo
echo "test play/pause/next/previous from the TV remote now."
echo "if remote control still doesn't reach the phone, or anything else"
echo "regressed (sync, dropouts, connect volume, credits), roll back with:"
echo "  ssh -t airplaymatrix-zero 'sudo bash ~/rollback-shairport-dev.sh'"
